# -*- coding: utf-8 -*-
"""Johnshall 广告（Reject）段 → overwrite/adblock/AdBlock_Domain.yaml、AdBlock_IP.yaml

与 Shadowrocket 配置同源，供 Clash Mi 覆写与 OpenClash LC_AdBlock 模块以 rule-provider 引用。
迁移自 mrc991/ShadowRocket-rules scripts/build_clash_adblock.py；去掉时间戳，内容不变时不产生提交。
"""
from __future__ import annotations

import ipaddress
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import build_shadowrocket as sr  # noqa: E402
import upstream  # noqa: E402

ROOT = upstream.ROOT
OUT_DIR = ROOT / "overwrite" / "adblock"
DOMAIN_OUT = OUT_DIR / "AdBlock_Domain.yaml"
IP_OUT = OUT_DIR / "AdBlock_IP.yaml"

# 上游抓取异常（空文件或截断）时宁可构建失败，也不发布残缺列表
MIN_DOMAINS = 20000

DOMAIN_RE = re.compile(r"^(?=.{1,253}$)([a-z0-9_](?:[a-z0-9_-]{0,61}[a-z0-9_])?\.)+[a-z0-9-]{2,63}$")


def extract(rule_lines: list[str]) -> tuple[list[str], list[str]]:
    ads, _rest = sr.split_johnshall_rules(rule_lines)
    domains: set[str] = set()
    cidrs: set[str] = set()
    for line in ads:
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        parts = [p.strip() for p in s.split(",")]
        if len(parts) < 3 or parts[2].upper() != "REJECT":
            continue
        rtype, val = parts[0].upper(), parts[1].lower().rstrip(".")
        if rtype in ("DOMAIN-SUFFIX", "DOMAIN"):
            if DOMAIN_RE.match(val):
                domains.add(("+." if rtype == "DOMAIN-SUFFIX" else "") + val)
        elif rtype in ("IP-CIDR", "IP-CIDR6"):
            try:
                cidrs.add(str(ipaddress.ip_network(val, strict=False)))
            except ValueError:
                continue
    return sorted(domains), sorted(cidrs, key=lambda c: (":" in c, c))


def render(kind: str, items: list[str]) -> str:
    j = upstream.JOHNSHALL
    head = [
        f"# Clash/Mihomo rule-provider ({kind}), generated by scripts/build_adblock.py",
        f"# SOURCE: https://github.com/{j['repo']}/blob/{j['ref']}/{j['path']} (Reject rules)",
        f"# TOTAL: {len(items)}",
        "payload:",
    ]
    return "\n".join(head + [f"  - '{x}'" for x in items]) + "\n"


def main() -> None:
    text, _sha = upstream.johnshall()
    domains, cidrs = extract(sr.split_sections(text).get("[Rule]", []))
    if len(domains) < MIN_DOMAINS:
        raise SystemExit(f"[build_adblock] FAILED: domains too few ({len(domains)} < {MIN_DOMAINS}); upstream looks broken")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DOMAIN_OUT.write_bytes(render("domain", domains).encode("utf-8"))
    IP_OUT.write_bytes(render("ipcidr", cidrs).encode("utf-8"))
    print(f"[build_adblock] wrote {DOMAIN_OUT.name} ({len(domains)}) and {IP_OUT.name} ({len(cidrs)})")


if __name__ == "__main__":
    main()
